#!/usr/bin/env node
/**
 * Build script to convert replacements.csv to a JavaScript module
 * that can be imported in both Node.js and browser environments.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const csvPath = path.join(__dirname, "replacements.csv");
const outputPath = path.join(__dirname, "data.js");

console.log("Building data.js from replacements.csv...");

const content = fs.readFileSync(csvPath, "utf-8");
const lines = content.split("\n").filter((line) => line.trim());

const entries = lines
  .slice(1) // Skip header
  .map((line) => {
    // Parse CSV with quoted fields: "value1","value2","value3"
    const match = line.match(/^"([^"]*)","([^"]*)","([^"]*)"$/);
    if (!match) {
      return null;
    }
    return {
      tibetan: match[1],
      transliteration: match[2],
      phonetics: match[3] || "",
    };
  })
  .filter(Boolean);

// Generate JavaScript module
const jsContent = `/**
 * Auto-generated from replacements.csv
 * Do not edit this file directly - edit replacements.csv and run build-data.js
 */

export const replacements = ${JSON.stringify(entries, null, 2)};

export default replacements;
`;

fs.writeFileSync(outputPath, jsContent, "utf-8");
console.log(`✓ Built data.js with ${entries.length} entries`);
